import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  integer,
  jsonb,
  pgPolicy,
  pgSequence,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { anonRole, authUid, authUsers, authenticatedRole } from "drizzle-orm/supabase";

// Postgres `timestamptz`, stored/returned as an ISO string.
const timestamptz = (name: string) =>
  timestamp(name, { withTimezone: true, mode: "string" });

/**
 * Sundusk database schema — spec section 5.
 *
 * Non-negotiables (do not relax these without re-reading section 5):
 * - All money is stored in paise as integers. Never a float, never a
 *   decimal column. Format for display only at render time.
 * - order_items denormalises product name, size, SKU and price at the time
 *   of order. Editing a product later must never change historical orders.
 * - orders.razorpay_payment_id is UNIQUE — this is the database-level
 *   idempotency guard against duplicate webhook delivery (section 7).
 * - Row Level Security is enabled on customers, addresses and orders, each
 *   with one SELECT policy scoped to auth.uid(). All writes go through
 *   server routes using the service role key (which bypasses RLS).
 */

// ---------------------------------------------------------------------------
// Order numbers: "SD1001", sequential, generated by Postgres — never by
// application code, or concurrent requests will collide (section 6).
// ---------------------------------------------------------------------------
export const orderNumberSeq = pgSequence("order_number_seq", {
  startWith: 1001,
  minValue: 1001,
  increment: 1,
});

// ---------------------------------------------------------------------------
// products
// ---------------------------------------------------------------------------
// RLS: enabled with a public, active-only SELECT policy. The storefront
// catalog is meant to be publicly readable, but Supabase grants anon and
// authenticated full SELECT/INSERT/UPDATE/DELETE on every public-schema
// table by default, independent of whether the app itself ever uses that
// access path — RLS was OFF here entirely until a live test with the
// real anon key proved this table (and product_variants, order_items,
// customization_requests, webhook_events below) was fully readable *and
// writable* by anyone on the internet with no login at all, via
// Supabase's autogenerated REST API, completely bypassing this app's own
// server code (which never goes through that API). Enabling RLS with
// only a SELECT policy blocks the INSERT/UPDATE/DELETE grants for
// anon/authenticated entirely; the app's own writes still work because
// its DB connection (DATABASE_URL, db/index.ts) authenticates as the
// `postgres` role, which owns these tables and bypasses RLS.
export const products = pgTable(
  "products",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    slug: text("slug").notNull().unique(),
    name: text("name").notNull(),
    description: text("description").notNull(),
    fabric: text("fabric"),
    fit: text("fit"),
    care: text("care"),
    // e.g. "Model is 5'6" and wears a size S"
    modelNote: text("model_note"),
    // Store money in paise, always an integer. ₹1,499 is 149900.
    pricePaise: integer("price_paise").notNull(),
    category: text("category").notNull(), // 'tops' | 'dresses'
    weightGrams: integer("weight_grams").notNull().default(250),
    hsnCode: text("hsn_code"),
    images: jsonb("images").$type<string[]>().notNull(),
    isActive: boolean("is_active").notNull().default(true),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamptz("created_at").notNull().defaultNow(),
    updatedAt: timestamptz("updated_at").notNull().defaultNow(),
  },
  (table) => [
    check("products_category_check", sql`${table.category} in ('tops', 'dresses')`),
    check("products_price_positive_check", sql`${table.pricePaise} > 0`),
    check("products_weight_positive_check", sql`${table.weightGrams} > 0`),
    pgPolicy("products_select_active", {
      for: "select",
      to: [anonRole, authenticatedRole],
      using: sql`${table.isActive} = true`,
    }),
  ],
).enableRLS();

// ---------------------------------------------------------------------------
// product_variants
// ---------------------------------------------------------------------------
// RLS: public SELECT (sizes/SKUs/stock counts aren't sensitive — the
// storefront already shows stock-derived availability per size), same
// reasoning as `products` above.
export const productVariants = pgTable(
  "product_variants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    size: text("size").notNull(), // 'XS' | 'S' | 'M' | 'L' | 'XL'
    sku: text("sku").notNull().unique(), // 'SD-TWT-XS'
    stock: integer("stock").notNull().default(0),
  },
  (table) => [
    unique("product_variants_product_size_unique").on(table.productId, table.size),
    check(
      "product_variants_size_check",
      sql`${table.size} in ('XS', 'S', 'M', 'L', 'XL')`,
    ),
    check("product_variants_stock_nonnegative_check", sql`${table.stock} >= 0`),
    pgPolicy("product_variants_select_all", {
      for: "select",
      to: [anonRole, authenticatedRole],
      using: sql`true`,
    }),
  ],
).enableRLS();

// ---------------------------------------------------------------------------
// customers — id matches Supabase auth.users.id
//
// RLS: signed-in customers may SELECT only their own row. There are no
// write policies — inserts/updates happen only through server routes using
// the service role key, which bypasses RLS entirely (Supabase's
// `service_role` has BYPASSRLS). See spec section 5.
//
// id references auth.users.id with onDelete: cascade — real FK, added in
// drizzle/0003_customers_auth_users_fk.sql (Drizzle can't generate a
// migration touching auth.users from a schema.ts diff, same reason the
// day-9 signup trigger is hand-written). Without this, deleting a
// Supabase Auth user leaves an orphaned customers row behind — found
// during day 9 testing (deleted a test auth user via the admin API,
// the matching customers row didn't go with it) rather than assumed.
// Matters beyond tidiness: the privacy policy (spec section 10A) promises
// "delete your account and personal data."
// ---------------------------------------------------------------------------
export const customers = pgTable(
  "customers",
  {
    id: uuid("id")
      .primaryKey()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    email: text("email").notNull().unique(),
    name: text("name"),
    phone: text("phone"),
    createdAt: timestamptz("created_at").notNull().defaultNow(),
  },
  (table) => [
    pgPolicy("customers_select_own", {
      for: "select",
      to: authenticatedRole,
      using: sql`${authUid} = ${table.id}`,
    }),
  ],
).enableRLS();

// ---------------------------------------------------------------------------
// addresses — RLS: customer may SELECT only rows whose customer_id is their
// own auth uid. Writes go through server routes with the service role key.
// ---------------------------------------------------------------------------
export const addresses = pgTable(
  "addresses",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    customerId: uuid("customer_id")
      .notNull()
      .references(() => customers.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    phone: text("phone").notNull(),
    line1: text("line1").notNull(),
    line2: text("line2"),
    city: text("city").notNull(),
    state: text("state").notNull(),
    pincode: text("pincode").notNull(),
    isDefault: boolean("is_default").notNull().default(false),
  },
  (table) => [
    pgPolicy("addresses_select_own", {
      for: "select",
      to: authenticatedRole,
      using: sql`${authUid} = ${table.customerId}`,
    }),
  ],
).enableRLS();

// ---------------------------------------------------------------------------
// orders — RLS: customer may SELECT only rows whose customer_id is their own
// auth uid. Guest orders (customer_id null) are never visible here; guests
// look their order up via the order-confirmation flow, not a customer
// session. Writes go through server routes with the service role key.
// ---------------------------------------------------------------------------
export const orders = pgTable(
  "orders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // 'SD1001' — generated by Postgres from order_number_seq, never in app code.
    orderNumber: text("order_number")
      .notNull()
      .unique()
      .default(sql`'SD' || nextval('order_number_seq')`),
    customerId: uuid("customer_id").references(() => customers.id), // null for guest checkout
    email: text("email").notNull(),
    phone: text("phone").notNull(),
    status: text("status").notNull().default("pending"),
    shippingName: text("shipping_name").notNull(),
    shippingLine1: text("shipping_line1").notNull(),
    shippingLine2: text("shipping_line2"),
    shippingCity: text("shipping_city").notNull(),
    shippingState: text("shipping_state").notNull(),
    shippingPincode: text("shipping_pincode").notNull(),
    subtotalPaise: integer("subtotal_paise").notNull(),
    shippingPaise: integer("shipping_paise").notNull().default(0),
    // Not in the original spec section 5 — added when a promo-code feature
    // was requested after checkout (day 6) already shipped. See lib/promo.ts
    // and docs/PROMO-AND-CUSTOM-FIT-NOTES.md.
    discountPaise: integer("discount_paise").notNull().default(0),
    promoCode: text("promo_code"),
    gstPaise: integer("gst_paise").notNull(),
    totalPaise: integer("total_paise").notNull(),
    razorpayOrderId: text("razorpay_order_id").unique(),
    // unique = idempotency guard against duplicate webhook delivery.
    razorpayPaymentId: text("razorpay_payment_id").unique(),
    courierName: text("courier_name"),
    trackingNumber: text("tracking_number"),
    adminNote: text("admin_note"),
    createdAt: timestamptz("created_at").notNull().defaultNow(),
    updatedAt: timestamptz("updated_at").notNull().defaultNow(),
  },
  (table) => [
    check(
      "orders_status_check",
      sql`${table.status} in ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded')`,
    ),
    check("orders_totals_nonnegative_check", sql`
      ${table.subtotalPaise} >= 0 and
      ${table.shippingPaise} >= 0 and
      ${table.discountPaise} >= 0 and
      ${table.gstPaise} >= 0 and
      ${table.totalPaise} >= 0
    `),
    pgPolicy("orders_select_own", {
      for: "select",
      to: authenticatedRole,
      using: sql`${authUid} = ${table.customerId}`,
    }),
  ],
).enableRLS();

// ---------------------------------------------------------------------------
// order_items — denormalised snapshot, must never change after the order
// is placed even if the product it references is edited later.
//
// RLS: enabled with zero policies — fully locked to anon/authenticated for
// every operation. Nothing in this app ever reads or writes order_items
// through Supabase's client-side API; every access goes through server
// code on the DATABASE_URL connection (db/index.ts), which bypasses RLS.
// There's no auth.uid() to scope a customer-owned SELECT policy to the way
// `orders` has one — order_items has no customer_id of its own, only a
// path through orders — so full lock is the correct default rather than
// leaving it open "because no policy fit."
// ---------------------------------------------------------------------------
export const orderItems = pgTable(
  "order_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "cascade" }),
    variantId: uuid("variant_id")
      .notNull()
      .references(() => productVariants.id),
    productName: text("product_name").notNull(),
    size: text("size").notNull(),
    sku: text("sku").notNull(),
    unitPricePaise: integer("unit_price_paise").notNull(), // price at time of order
    quantity: integer("quantity").notNull(),
  },
  (table) => [
    check("order_items_quantity_positive_check", sql`${table.quantity} > 0`),
    check("order_items_price_nonnegative_check", sql`${table.unitPricePaise} >= 0`),
  ],
).enableRLS();

// ---------------------------------------------------------------------------
// customization_requests — not in the original spec. Added when a beyond-XL
// made-to-order feature was requested after the core build was underway.
// This is a lead-capture table, not an order: no stock concept, no
// payment happens here. Staff review requests in admin and arrange payment
// separately once feasibility/timeline is confirmed. See
// docs/PROMO-AND-CUSTOM-FIT-NOTES.md for the full reasoning, including why
// this isn't wired into the `orders` table.
//
// RLS: enabled with zero policies — fully locked to anon/authenticated.
// An earlier version of this comment argued RLS wasn't needed here because
// "only admin (service role key) ever reads this table" — that reasoning
// was wrong and left this table (real PII: name, email, phone, body
// measurements) fully readable *and writable* by anyone with the public
// anon key, via Supabase's REST API, which the service-role reasoning
// never accounted for. "The app only reads it via the service role" and
// "only the service role CAN read it" are not the same claim — RLS is
// what makes the second one true. Fixed alongside the same gap on
// `product_variants`, `order_items`, and `webhook_events`.
// ---------------------------------------------------------------------------
export const customizationRequests = pgTable(
  "customization_requests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id").references(() => products.id),
    productName: text("product_name").notNull(), // denormalised, like order_items
    name: text("name").notNull(),
    email: text("email").notNull(),
    phone: text("phone").notNull(),
    bustIn: integer("bust_in"),
    waistIn: integer("waist_in"),
    hipsIn: integer("hips_in"),
    notes: text("notes").notNull(),
    status: text("status").notNull().default("new"), // 'new' | 'contacted' | 'closed'
    adminNote: text("admin_note"),
    createdAt: timestamptz("created_at").notNull().defaultNow(),
    updatedAt: timestamptz("updated_at").notNull().defaultNow(),
  },
  (table) => [
    check(
      "customization_requests_status_check",
      sql`${table.status} in ('new', 'contacted', 'closed')`,
    ),
    check(
      "customization_requests_measurements_check",
      sql`
        (${table.bustIn} is null or ${table.bustIn} between 20 and 70) and
        (${table.waistIn} is null or ${table.waistIn} between 20 and 70) and
        (${table.hipsIn} is null or ${table.hipsIn} between 20 and 70)
      `,
    ),
  ],
).enableRLS();

// ---------------------------------------------------------------------------
// webhook_events — dedupe guard for Razorpay webhook delivery (section 7).
//
// RLS: enabled with zero policies — fully locked. This table's payload
// column holds full Razorpay webhook bodies (payment IDs, order IDs,
// amounts); its unique razorpay_event_id is also the idempotency guard
// against duplicate webhook delivery — anon DELETE access here (present
// by default without RLS, same as every other table on this page) would
// let someone erase a dedupe row and force a captured payment to be
// reprocessed. Only the webhook route and admin ever need this table, both
// via the server's DATABASE_URL connection, which bypasses RLS regardless.
// ---------------------------------------------------------------------------
export const webhookEvents = pgTable(
  "webhook_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    razorpayEventId: text("razorpay_event_id").notNull().unique(),
    eventType: text("event_type").notNull(),
    payload: jsonb("payload").notNull(),
    processedAt: timestamptz("processed_at"),
    createdAt: timestamptz("created_at").notNull().defaultNow(),
  },
  () => [],
).enableRLS();

// ---------------------------------------------------------------------------
// stock_movements — audit trail for every change to a variant's stock
// count, admin panel v2 (not in the original spec). Pulled forward from
// its own planned phase because the paid -> refunded restock below
// depends on it existing.
//
// No FK onDelete on variant_id: deliberately NOT cascading. A variant is
// never expected to be deleted in this app (products are archived, not
// hard-deleted — see the admin-v2 product-delete phase), and if that
// assumption is ever wrong, the right failure mode for an audit table is
// "the delete is blocked" (Postgres's default NO ACTION), not "the
// history silently vanishes with it."
//
// admin_email is nullable on purpose: a system-triggered movement (an
// order being paid, or refunded/restocked) has no admin acting — only a
// 'manual' edit from the new stock page has one.
//
// RLS: enabled with zero policies from the start, per the security audit
// (docs/SECURITY-AUDIT-NOTES.md) — every table added after that audit
// gets this from day one rather than being another gap to find later.
// ---------------------------------------------------------------------------
export const stockMovements = pgTable(
  "stock_movements",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    variantId: uuid("variant_id")
      .notNull()
      .references(() => productVariants.id),
    delta: integer("delta").notNull(), // positive = added, negative = removed
    reason: text("reason").notNull(), // 'manual' | 'order_paid' | 'order_cancelled' | 'restock'
    adminEmail: text("admin_email"),
    note: text("note"),
    createdAt: timestamptz("created_at").notNull().defaultNow(),
  },
  (table) => [
    check(
      "stock_movements_reason_check",
      sql`${table.reason} in ('manual', 'order_paid', 'order_cancelled', 'restock')`,
    ),
    check("stock_movements_delta_nonzero_check", sql`${table.delta} != 0`),
  ],
).enableRLS();
